version: "3.1"
services:
    memcached:
      image: memcached:alpine
      container_name: acc_memcached

    mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: acc_mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=password
      ports:
        - "3206:3306"

    webserver:
      image: nginx:alpine
      container_name: acc_webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "3200:80"

    php-fpm:
      image: crunchgeek/php-fpm:8.2
      container_name: acc_phpfpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./sessions:/var/lib/php/sessions

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: acc_phpmyadmin
      restart: always
      ports:
        - "3209:80"
      environment:
        PMA_HOST: mysql
